### ISSUE TITLE
Palvelut ja huolto sivu

### ISSUE THREAD

**Issue by Marikaverger** [Tomi-Salminen/Ohjelmistoprojekti#11]
Oma sivu, josta löytyy palvelut ja huoltoasiat

**Comment by Tomi-Salminen** [comment]
- [ ] Kotisivun kuvaa painamalla pääsee sivulle
- [ ] Sivulla on esittelyteksti tarjotuille palveluille
- [ ] Sivulla esitellään kolme palvelupakettivaihtoehtoa
- [ ] Taulukkovertailu palvelupakettien välillä
- [ ] Eri näkymä sisäänkirjautuneille käyttäjille --> palvelupaketin voi valita suoraan tilaukseen?
